export const currencies = [
    
  { country: "Pakistan", code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
  { country: "Afghanistan", code: "AFN", name: "Afghan Afghani", symbol: "؋" },
  { country: "United States", code: "USD", name: "United States Dollar", symbol: "$" },
  { country: "Albania", code: "ALL", name: "Albanian Lek", symbol: "L" },
  { country: "Algeria", code: "DZD", name: "Algerian Dinar", symbol: "د.ج" },
  { country: "Andorra", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Angola", code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
  { country: "Armenia", code: "AMD", name: "Armenian Dram", symbol: "֏" },
  { country: "Austria", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Azerbaijan", code: "AZN", name: "Azerbaijani Manat", symbol: "₼" },
  { country: "Bahamas", code: "BSD", name: "Bahamian Dollar", symbol: "$" },
  { country: "Bahrain", code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب" },
  { country: "Bangladesh", code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { country: "Barbados", code: "BBD", name: "Barbadian Dollar", symbol: "$" },
  { country: "Belarus", code: "BYN", name: "Belarusian Ruble", symbol: "Br" },
  { country: "Belgium", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Belize", code: "BZD", name: "Belize Dollar", symbol: "$" },
  { country: "Benin", code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { country: "Bhutan", code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu." },
  { country: "Bolivia", code: "BOB", name: "Bolivian Boliviano", symbol: "Bs." },
  { country: "Bosnia and Herzegovina", code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
  { country: "Botswana", code: "BWP", name: "Botswanan Pula", symbol: "P" },
  { country: "Brazil", code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { country: "Brunei", code: "BND", name: "Brunei Dollar", symbol: "$" },
  { country: "Bulgaria", code: "BGN", name: "Bulgarian Lev", symbol: "лв." },
  { country: "Burkina Faso", code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { country: "Burundi", code: "BIF", name: "Burundian Franc", symbol: "Fr" },
  { country: "Cabo Verde", code: "CVE", name: "Cape Verdean Escudo", symbol: "$" },
  { country: "Cambodia", code: "KHR", name: "Cambodian Riel", symbol: "៛" },
  { country: "Cameroon", code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
  { country: "Canada", code: "CAD", name: "Canadian Dollar", symbol: "$" },
  { country: "Chad", code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
  { country: "Chile", code: "CLP", name: "Chilean Peso", symbol: "$" },
  { country: "China", code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { country: "Colombia", code: "COP", name: "Colombian Peso", symbol: "$" },
  { country: "Comoros", code: "KMF", name: "Comorian Franc", symbol: "CF" },
  { country: "Congo (Congo-Brazzaville)", code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
  { country: "Costa Rica", code: "CRC", name: "Costa Rican Colón", symbol: "₡" },
  { country: "Croatia", code: "HRK", name: "Croatian Kuna", symbol: "kn" },
  { country: "Cuba", code: "CUP", name: "Cuban Peso", symbol: "$" },
  { country: "Cyprus", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Czech Republic", code: "CZK", name: "Czech Koruna", symbol: "Kč" },
  { country: "Denmark", code: "DKK", name: "Danish Krone", symbol: "kr" },
  { country: "Djibouti", code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" }, 
  { country: "Dominica", code: "XCD", name: "East Caribbean Dollar", symbol: "$" },
  { country: "Dominican Republic", code: "DOP", name: "Dominican Peso", symbol: "$" },
  // { country: "Ecuador", code: "USD", name: "United States Dollar", symbol: "$" },
  { country: "Egypt", code: "EGP", name: "Egyptian Pound", symbol: "ج.م" },
  // { country: "El Salvador", code: "USD", name: "United States Dollar", symbol: "$" },
  { country: "Estonia", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Eswatini", code: "SZL", name: "Swazi Lilangeni", symbol: "L" },
  { country: "Ethiopia", code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
  { country: "Fiji", code: "FJD", name: "Fijian Dollar", symbol: "$" },
  { country: "Finland", code: "EUR", name: "Euro", symbol: "€" },
  { country: "France", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Gabon", code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
  { country: "Gambia", code: "GMD", name: "Gambian Dalasi", symbol: "D" },
  { country: "Georgia", code: "GEL", name: "Georgian Lari", symbol: "₾" },
  { country: "Germany", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Ghana", code: "GHS", name: "Ghanaian Cedi", symbol: "₵" },
  { country: "Greece", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Guatemala", code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
  { country: "Guinea", code: "GNF", name: "Guinean Franc", symbol: "FG" },
  { country: "Guyana", code: "GYD", name: "Guyanese Dollar", symbol: "$" },
  { country: "Haiti", code: "HTG", name: "Haitian Gourde", symbol: "G" },
  { country: "Honduras", code: "HNL", name: "Honduran Lempira", symbol: "L" },
  { country: "Hungary", code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
  { country: "Iceland", code: "ISK", name: "Icelandic Krona", symbol: "kr" },
  { country: "India", code: "INR", name: "Indian Rupee", symbol: "₹" },
  { country: "Indonesia", code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { country: "Iran", code: "IRR", name: "Iranian Rial", symbol: "﷼" },
  { country: "Iraq", code: "IQD", name: "Iraqi Dinar", symbol: "ع.د" },
  { country: "Ireland", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Israel", code: "ILS", name: "Israeli New Shekel", symbol: "₪" },
  { country: "Italy", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Jamaica", code: "JMD", name: "Jamaican Dollar", symbol: "$" },
  { country: "Japan", code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { country: "Jordan", code: "JOD", name: "Jordanian Dinar", symbol: "د.أ" },
  { country: "Kazakhstan", code: "KZT", name: "Kazakhstani Tenge", symbol: "₸" },
  { country: "Kenya", code: "KES", name: "Kenyan Shilling", symbol: "Ksh" },
  { country: "Kuwait", code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
  { country: "Kyrgyzstan", code: "KGS", name: "Kyrgyzstani Som", symbol: "с" },
  { country: "Laos", code: "LAK", name: "Lao Kip", symbol: "₭" },
  { country: "Latvia", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Lebanon", code: "LBP", name: "Lebanese Pound", symbol: "ل.ل" },
  { country: "Lesotho", code: "LSL", name: "Lesotho Loti", symbol: "L" },
  { country: "Liberia", code: "LRD", name: "Liberian Dollar", symbol: "$" },
  { country: "Libya", code: "LYD", name: "Libyan Dinar", symbol: "ل.د" },
  { country: "Liechtenstein", code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { country: "Lithuania", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Luxembourg", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Madagascar", code: "MGA", name: "Malagasy Ariary", symbol: "Ar" },
  { country: "Malawi", code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
  { country: "Malaysia", code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { country: "Maldives", code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf" },
  { country: "Mali", code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { country: "Malta", code: "EUR", name: "Euro", symbol: "€" },
  // { country: "Marshall Islands", code: "USD", name: "United States Dollar", symbol: "$" },
  { country: "Mauritania", code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM" },
  { country: "Mauritius", code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
  { country: "Mexico", code: "MXN", name: "Mexican Peso", symbol: "$" },
  // { country: "Micronesia", code: "USD", name: "United States Dollar", symbol: "$" },
  { country: "Moldova", code: "MDL", name: "Moldovan Leu", symbol: "L" },
  { country: "Monaco", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Mongolia", code: "MNT", name: "Mongolian Tögrög", symbol: "₮" },
  { country: "Montenegro", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Morocco", code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
  { country: "Mozambique", code: "MZN", name: "Mozambican Metical", symbol: "MT" },
  { country: "Myanmar", code: "MMK", name: "Myanmar Kyat", symbol: "Ks" },
  { country: "Namibia", code: "NAD", name: "Namibian Dollar", symbol: "$" },
  { country: "Nepal", code: "NPR", name: "Nepalese Rupee", symbol: "₨" },
  { country: "Netherlands", code: "EUR", name: "Euro", symbol: "€" },
  { country: "New Zealand", code: "NZD", name: "New Zealand Dollar", symbol: "$" },
  { country: "Nicaragua", code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$" },
  { country: "Niger", code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { country: "Nigeria", code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { country: "North Korea", code: "KPW", name: "North Korean Won", symbol: "₩" },
  { country: "North Macedonia", code: "MKD", name: "Macedonian Denar", symbol: "ден" },
  { country: "Norway", code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { country: "Oman", code: "OMR", name: "Omani Rial", symbol: "ر.ع." },
  // { country: "Palau", code: "USD", name: "United States Dollar", symbol: "$" },
  { country: "Panama", code: "PAB", name: "Panamanian Balboa", symbol: "B/." },
  { country: "Papua New Guinea", code: "PGK", name: "Papua New Guinean Kina", symbol: "K" },
  { country: "Paraguay", code: "PYG", name: "Paraguayan Guarani", symbol: "₲" },
  { country: "Peru", code: "PEN", name: "Peruvian Sol", symbol: "S/" },
  { country: "Philippines", code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { country: "Poland", code: "PLN", name: "Polish Zloty", symbol: "zł" },
  { country: "Portugal", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Qatar", code: "QAR", name: "Qatari Rial", symbol: "ر.ق" },
  { country: "Romania", code: "RON", name: "Romanian Leu", symbol: "lei" },
  { country: "Russia", code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { country: "Rwanda", code: "RWF", name: "Rwandan Franc", symbol: "FRw" },
  { country: "Saint Kitts and Nevis", code: "XCD", name: "East Caribbean Dollar", symbol: "$" },
  { country: "Saint Lucia", code: "XCD", name: "East Caribbean Dollar", symbol: "$" },
  { country: "Saint Vincent and the Grenadines", code: "XCD", name: "East Caribbean Dollar", symbol: "$" },
  { country: "Samoa", code: "WST", name: "Samoan Tala", symbol: "T" },
  { country: "San Marino", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Sao Tome and Principe", code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { country: "Saudi Arabia", code: "SAR", name: "Saudi Riyal", symbol: "ر.س" },
  { country: "Senegal", code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { country: "Serbia", code: "RSD", name: "Serbian Dinar", symbol: "дин." },
  { country: "Seychelles", code: "SCR", name: "Seychellois Rupee", symbol: "₨" },
  { country: "Sierra Leone", code: "SLL", name: "Sierra Leonean Leone", symbol: "Le" },
  { country: "Singapore", code: "SGD", name: "Singapore Dollar", symbol: "$" },
  { country: "Slovakia", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Slovenia", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Somalia", code: "SOS", name: "Somali Shilling", symbol: "S" },
  { country: "South Africa", code: "ZAR", name: "South African Rand", symbol: "R" },
  { country: "South Korea", code: "KRW", name: "South Korean Won", symbol: "₩" },
  { country: "South Sudan", code: "SSP", name: "South Sudanese Pound", symbol: "£" },
  { country: "Spain", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Sri Lanka", code: "LKR", name: "Sri Lankan Rupee", symbol: "₨" },
  { country: "Sudan", code: "SDG", name: "Sudanese Pound", symbol: "ج.س." },
  { country: "Suriname", code: "SRD", name: "Surinamese Dollar", symbol: "$" },
  { country: "Sweden", code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { country: "Switzerland", code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { country: "Syria", code: "SYP", name: "Syrian Pound", symbol: "ل.س" },
  { country: "Taiwan", code: "TWD", name: "New Taiwan Dollar", symbol: "NT$" },
  { country: "Tajikistan", code: "TJS", name: "Tajikistani Somoni", symbol: "SM" },
  { country: "Tanzania", code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
  { country: "Thailand", code: "THB", name: "Thai Baht", symbol: "฿" },
  { country: "Togo", code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { country: "Tonga", code: "TOP", name: "Tongan Paʻanga", symbol: "T$" },
  { country: "Trinidad and Tobago", code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "$" },
  { country: "Tunisia", code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
  { country: "Turkey", code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { country: "Turkmenistan", code: "TMT", name: "Turkmenistani Manat", symbol: "T" },
  { country: "Uganda", code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
  { country: "Ukraine", code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
  { country: "United Arab Emirates", code: "AED", name: "United Arab Emirates Dirham", symbol: "د.إ" },
  { country: "United Kingdom", code: "GBP", name: "British Pound Sterling", symbol: "£" },
 
  { country: "Uruguay", code: "UYU", name: "Uruguayan Peso", symbol: "$" },
  { country: "Uzbekistan", code: "UZS", name: "Uzbekistani Som", symbol: "лв" },
  { country: "Vanuatu", code: "VUV", name: "Vanuatu Vatu", symbol: "Vt" },
  { country: "Vatican City", code: "EUR", name: "Euro", symbol: "€" },
  { country: "Venezuela", code: "VES", name: "Venezuelan Bolívar", symbol: "Bs" },
  { country: "Vietnam", code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { country: "Yemen", code: "YER", name: "Yemeni Rial", symbol: "ر.ي" },
  { country: "Zambia", code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" },
  { country: "Zimbabwe", code: "ZWL", name: "Zimbabwean Dollar", symbol: "$" }
];
